name: AppImage Release
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1
        with:
          # Optional, relative to workspace directory
          source_directory: lolcat
          # Optional, relative to workspace directory
          artifacts_directory: output
