name: Deb Release
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1
